### ISSUE TITLE
No guideline to use the scripts

### ISSUE THREAD

**Issue by nianik5098** [albertz/helpers#1]
I would like to know how to use the indent-spacestotabs.py from command line. I have been trying different combinations but in vain. (I am newbie in python)

**Comment by albertz** [comment]
`indent-spacestotabs.py` (without parameters) should give you an usage description. Basically the parameters are `-n <spacenum> [-i] [infile]`. `-i` means inplace. Example:
```
indent-spacestotabs.py -n 4 -i your_script_to_transform.py
```
That will edit the file `your_script_to_transform.py` and changes all spaces of width 4 to tabs.
