### ISSUE TITLE
In `git-find-related-commits`, counting of added/deleted lines is slightly wrong

### ISSUE THREAD

**Issue by akaihola** [albertz/helpers#2]
My [comment](/albertz/helpers/commit/d4eb182266b4e4cdd5b879f5f9094cf24eea3b4f#r95381383) to commit d4eb182266b4e4cdd5b879f5f9094cf24eea3b4f which added `+`/`-` counting:

>This is slightly wrong, at least with recent Git versions. There is actually no space between the `+` or `-` and the content of the line. So you need to first discard the `---` and `+++` lines of the header, and then count lines starting with just `+` or `-`.

This is the code I was commenting:
```python
def _count_changed_lines(s: str) -> int:
  c = 0
  for line in s.splitlines():
    if line.startswith("+ ") or line.startswith("- "):
      c += 1
  return c
```

I've been experimenting with your code, and my current version (see [akaihola/git-find-related-commits](/akaihola/git-find-related-commits)) of the function is:
```python
def _count_changed_lines(s: str) -> int:
    lines = s.splitlines()
    assert lines[0].startswith("diff --git ")
    if lines[1].startswith(("new file ", "deleted file ")):
        lines.pop(1)
    assert lines[1].startswith("index ")
    assert lines[2].startswith("--- ")
    assert lines[3].startswith("+++ ")
    return sum(1 for line in lines[4:] if line.startswith(("+", "-")))
```

It accepts output from `repo.git.diff()` and `repo.git.show()`, but with the latter it's important to switch off the commit header using the `format=` option:
```python
self.repo.git.show(commit2, format="")
```

**Comment by albertz** [comment]
Thanks.

I wonder, as you have now a separate repo just for this tool, whether I should remove the file here so that we have only one version. It's unlikely that I will put much further work into this, at least in the near future. So I don't really see much value that our code diverges now. Regarding licence, is MIT fine?

**Comment by akaihola** [comment]
MIT is fine. I would like to turn the script in my repo into an installable Python package and upload it to the PyPI, if that's ok for you.

Once there is a pip-installable version of it, maybe you could keep the old file in your repo, add
```python
import git_find_related_commits  # pip install git-find-related-commits
```
and just turn the main program to
```python
git_find_related_commits.main()
```
(or whatever the entry point will be)?

**Comment by albertz** [comment]
I added the MIT licence in the root of helpers.

In your repo, it would be nice to add an appropriate copyright notice mentioning my name, and then your name, and the MIT licence.

I think I will just remove the file here and in the readme, refer to your repo.

A pip package for the tool is a good idea.

I'm just not really sure how much users are there for this. After the time I developed this, you are the first who has shown any interest in it.

**Comment by akaihola** [comment]
Thanks! I'll add the copyright notice, our names and the MIT license.

I wonder why others haven't found the tool. I've started to more and more use a workflow where I make frequent small commits, and later squash related ones together to make reviewing easier for my colleagues. Browsing back and forth and comparing commits manually is slow, and your tool is able to speed up the process a lot.

**Comment by akaihola** [comment]
Copyright added in [36a82aa2](/akaihola/git-find-related-commits/commit/36a82aa2b86832aa3848d4dddbcdcc56b44fbcff), license in [76f765d5](/akaihola/git-find-related-commits/commit/76f765d58a236b05af95887d936200fcf14dec9d).

**Comment by albertz** [comment]
Thanks. I removed the file now here in the repo and added a reference to your repo in the readme.

**Comment by albertz** [comment]
Also thanks for properly preserving the original Git history.

**Comment by albertz** [comment]
Maybe you can also add a short README. Adding the links I have in the docstring, and maybe a ref to the repo here and its history.

**Comment by akaihola** [comment]
I'll be sure to add that as well. Tracking in akaihola/git-find-related-commits#1.
